/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "iostream"
/* Header for class com_lll_commonjni_NDKCppInteface */

#ifndef _Included_com_lll_commonjni_NDKCppInteface
#define _Included_com_lll_commonjni_NDKCppInteface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lll_commonjni_NDKCppInteface
 * Method:    executeCppConst
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lll_commonjni_NDKCppInteface_executeCppConst
        (JNIEnv *, jobject);


/*
 * Class:     com_lll_commonjni_NDKCppInteface
 * Method:    executeCppFuncPointer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lll_commonjni_NDKCppInteface_executeCppFuncPointer
        (JNIEnv *, jobject);


/*
 * Class:     com_lll_commonjni_NDKCppInteface
 * Method:    executeCppFuncPointer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lll_commonjni_NDKCppInteface_executeCppClass
        (JNIEnv *, jobject);


/*
 * Class:     com_lll_commonjni_NDKCppInteface
 * Method:    executeCppFuncPointer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lll_commonjni_NDKCppInteface_executeCppCopy
        (JNIEnv *, jobject);

/*
 * 对象属性的初始化
 * Class:     com_lll_commonjni_NDKCppInteface
 * Method:    initObjectAttribute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lll_commonjni_NDKCppInteface_initObjectAttribute
        (JNIEnv *, jobject);

/*
 * static 关键字
 * Class:     com_lll_commonjni_NDKCppInteface
 * Method:    executeStaticKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lll_commonjni_NDKCppInteface_executeStaticKey
        (JNIEnv *, jobject); //

/*
 * static  指针和引用的区别
 * Class:     com_lll_commonjni_NDKCppInteface
 * Method:    executeStaticKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lll_commonjni_NDKCppInteface_callCppPointerAndRefDiff
        (JNIEnv *, jobject);

//callCppOperator
/*
 * static  C++ 中的运算符操作 重载 重写
 * Class:     com_lll_commonjni_NDKCppInteface
 * Method:    callCppOperator
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lll_commonjni_NDKCppInteface_callCppOperator
        (JNIEnv *, jobject);
//callCppBackets
/*
 * static  ()运算符 重写
 * Class:     com_lll_commonjni_NDKCppInteface
 * Method:    callCppOperator
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lll_commonjni_NDKCppInteface_callCppBackets
        (JNIEnv *, jobject);

//
/*
 * static  继承 初始化父类属性
 * Class:     com_lll_commonjni_NDKCppInteface
 * Method:    callCppOperator
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lll_commonjni_NDKCppInteface_callCppextends
        (JNIEnv *, jobject);

//
/*
 * static  C++ 的抽象类（纯虚构函数）
 * Class:     com_lll_commonjni_NDKCppInteface
 * Method:    callCppAbstractClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lll_commonjni_NDKCppInteface_callCppAbstractClass
        (JNIEnv *, jobject);


/*
 * static  C++ 抽象类 虚构函数
 * Class:     com_lll_commonjni_NDKCppInteface
 * Method:    callCppAbstractClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lll_commonjni_NDKCppInteface_callCppAbstractClass
        (JNIEnv *, jobject);

//callFuncPointer
/*
 * static  C++ 的函数指针作为函数参数
 * Class:     com_lll_commonjni_NDKCppInteface
 * Method:    callCppAbstractClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lll_commonjni_NDKCppInteface_callFuncPointer
        (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
