/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lll_commonjni_NDKCppInteface */

#ifndef _Included_com_lll_commonjni_NDKCppInteface
#define _Included_com_lll_commonjni_NDKCppInteface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lll_commonjni_NDKCppInteface
 * Method:    executeCppConst
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lll_commonjni_NDKCppInteface_executeCppConst
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
