/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lll_commonjni_utils_JNIUtils */

#ifndef _Included_com_lll_commonjni_utils_JNIUtils
#define _Included_com_lll_commonjni_utils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lll_commonjni_utils_JNIUtils
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lll_commonjni_utils_JNIUtils_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
